### ISSUE TITLE
information bottleneck and blahut arimoto

### ISSUE THREAD

**Issue by cskemp** [dit/dit#155]
The ba method doesn't seem to work for the information bottleneck when x and y have different numbers of values (ie p_xy is not square). For example 

d = dit.Distribution(['00', '02', '11'], [1/3]*3)
IBCurve(d, beta_num=26, method='ba').plot()

produces the error

  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dit/rate_distortion/blahut_arimoto.py", line 194, in distortion
    distortions = np.asarray([divergence(a, b) for a in p_y_x for b in q_y_t]).reshape(q_y_t.shape)
ValueError: cannot reshape array of size 4 into shape (2,3)

but 

d = dit.Distribution(['00', '02', '11'], [1/3]*3)
IBCurve(d, beta_num=26, method='sp').plot()

works fine

(using Python 3.6, MacOS 10.13.6)

**Comment by Autoplectic** [comment]
Thank you, i'll look in to this.

**Comment by epiasini** [comment]
For the record, I noticed another oddity in the behavior of the BA algorithm. In the specific case of 2x2 distributions, it raises an `InvalidNormalization` exception:

```
Python 3.8.3 (default, Jun 29 2020, 17:45:03) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dit
>>> from dit.rate_distortion import IBCurve
>>> d = dit.Distribution.from_ndarray([[0.1, 0.4],[0.35, 0.15]])
>>> dit.rate_distortion.IBCurve(d, method='ba')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eugenio/virtualenvs/openblas/lib/python3.8/site-packages/dit/rate_distortion/curves.py", line 353, in __init__
    self.compute(method)
  File "/home/eugenio/virtualenvs/openblas/lib/python3.8/site-packages/dit/rate_distortion/curves.py", line 450, in compute
    d = Distribution.from_ndarray(q_xyzt)
  File "/home/eugenio/virtualenvs/openblas/lib/python3.8/site-packages/dit/npdist.py", line 681, in from_ndarray
    return cls(*zip(*np.ndenumerate(ndarray)), base=base, prng=prng)
  File "/home/eugenio/virtualenvs/openblas/lib/python3.8/site-packages/dit/npdist.py", line 508, in __init__
    self.validate()
  File "/home/eugenio/virtualenvs/openblas/lib/python3.8/site-packages/dit/npscalardist.py", line 1848, in validate
    getattr(self, method)()
  File "/home/eugenio/virtualenvs/openblas/lib/python3.8/site-packages/dit/distribution.py", line 401, in _validate_normalization
    v = validate_normalization(self.pmf, self.ops)
  File "/home/eugenio/virtualenvs/openblas/lib/python3.8/site-packages/dit/validate.py", line 87, in validate_normalization
    raise InvalidNormalization(total)
dit.exceptions.InvalidNormalization: <exception str() failed>
```
There is no error with `method='sp'`, or if the distribution is larger (I tried 3x3 and 4x4).
