### ISSUE TITLE
ValueError: `x0` violates bound constraints in PID Example

### ISSUE THREAD

**Issue by juancarlosfarah** [dit/dit#184]
**Describe the Bug**

I'm getting an error when running one of the [example scripts](https://github.com/dit/dit/blob/master/examples/PID.ipynb) locally inside a `virtualenv`.

The script consists of the following snippet of code, which I have under a file named `pid.py`.

```python
import dit
from dit.pid.helpers import compare_measures
from dit.pid.distributions import bivariates, trivariates
dit.ditParams['print.exact'] = dit.ditParams['repr.print'] = True
dit.ditParams['text.font'] = 'linechar'

for name, dist in bivariates.items():
    compare_measures(dist, name=name)
```

When I run it, I get the following error:

```
Traceback (most recent call last):
  File ".../pid.py", line 8, in <module>
    compare_measures(dist, name=name)
  File ".../venv/lib/python3.9/site-packages/dit/pid/helpers.py", line 41, in compare_measures
    pids = [pid(dist.copy(), inputs, output) for pid in pids]
  File ".../venv/lib/python3.9/site-packages/dit/pid/helpers.py", line 41, in <listcomp>
    pids = [pid(dist.copy(), inputs, output) for pid in pids]
  File ".../venv/lib/python3.9/site-packages/dit/pid/pid.py", line 126, in __init__
    self._compute()
  File ".../venv/lib/python3.9/site-packages/dit/pid/pid.py", line 596, in _compute
    uniques = self._measure(self._dist, self._inputs, self._output, **self._kwargs)
  File ".../venv/lib/python3.9/site-packages/dit/pid/measures/iskar.py", line 134, in _measure
    uniques[source] = one_way_skar(d, target, source, others)
  File ".../venv/lib/python3.9/site-packages/dit/utils/units.py", line 72, in wrapper
    value = f(*args, **kwargs)
  File ".../venv/lib/python3.9/site-packages/dit/multivariate/secret_key_agreement/one_way_skar.py", line 111, in one_way_skar
    nimi.optimize(niter=niter)
  File ".../venv/lib/python3.9/site-packages/dit/algorithms/optimization.py", line 773, in optimize
    self._polish(cutoff=polish)
  File ".../venv/lib/python3.9/site-packages/dit/algorithms/optimization.py", line 864, in _polish
    res = minimize(fun=self.objective,
  File ".../venv/lib/python3.9/site-packages/scipy/optimize/_minimize.py", line 619, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File ".../venv/lib/python3.9/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File ".../venv/lib/python3.9/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File ".../venv/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in __init__
    self._update_grad()
  File ".../venv/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 231, in _update_grad
    self._update_grad_impl()
  File ".../venv/lib/python3.9/site-packages/scipy/optimize/_differentiable_functions.py", line 151, in update_grad
    self.g = approx_derivative(fun_wrapped, self.x, f0=self.f,
  File ".../venv/lib/python3.9/site-packages/scipy/optimize/_numdiff.py", line 451, in approx_derivative
    raise ValueError("`x0` violates bound constraints.")
ValueError: `x0` violates bound constraints.
```

**To Reproduce**

- Create a virtualenv with Python 3
```
python3 -m venv venv
```
- Activate the virtualenv
```
source ./venv/bin/activate
```
- Install `dit` from the `master` branch
```
pip install git+https://github.com/dit/dit
```
- Paste the code above into a file (e.g. `pid.py`).
- Run `pid.py`
```
python pid.py
```

**Expected Behavior**

The example from the Jupyter notebook runs as expected.

**Additional Context**

This error follows from #183.

**Comment by Autoplectic** [comment]
Hi @juancarlosfarah. I think this is fixed in master now. The long and short of it is that changes to how scipy does its minimizations require the optimization vector to not mutate during the calculation of the objective. this didn't use to be the case. anyway, turns out that just throwing a `x.copy()` in the appropriate location fixes things.

I'm hoping to get a couple new decompositions added soon, as well as maybe a new pid measure, then i'll cut a new release.
